### ISSUE TITLE
Crash in rename dialog on device rotation

### ISSUE THREAD

**Issue by xandro0777** [k3b/APhotoManager#139]
* select image
* menu/rename
* rotate device to landscape
* edit name, DONE
* rotate device to normal position again
* press OK in rename menu
-> crash

hope this log extract gives you enough information:
```
[ 03-15 23:08:43.638 18124:18193 D/ImageLoader ]
Start display image task [file:///storage/emulated/0/DCIM/OpenCamera/IMG_20190228_122402.jpg_720x1184]

[ 03-15 23:08:43.639 18124:18193 D/ImageLoader ]
Load image from disk cache [file:///storage/emulated/0/DCIM/OpenCamera/IMG_20190228_122402.jpg_720x1184]

[ 03-15 23:08:43.639 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#IMG_20190228_122402.jpg:setImageViewMatrix setRotationTo 0.0

[ 03-15 23:08:43.654 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#Vogel.Gezwitscher.Screenshot_2019-03-12-16-28-46.png:setImageViewMatrix setRotationTo 0.0

[ 03-15 23:08:43.654 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#Vogel.Gezwitscher.Screenshot_2019-03-12-16-28-46.png:setImageViewMatrix onGlobalLayout mZoomEnabled=true-resetMatrix

[ 03-15 23:08:43.654 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#Teller.Gerausch_2019-03-15-11-38-15.png:setImageViewMatrix setRotationTo 0.0

[ 03-15 23:08:43.655 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#Teller.Gerausch_2019-03-15-11-38-15.png:setImageViewMatrix onGlobalLayout mZoomEnabled=true-resetMatrix

[ 03-15 23:08:43.655 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#IMG_20190228_122402.jpg:setImageViewMatrix setRotationTo 0.0

[ 03-15 23:08:43.655 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#IMG_20190228_122402.jpg:setImageViewMatrix onGlobalLayout mZoomEnabled=true-resetMatrix

[ 03-15 23:08:43.806 18124:18124 D/ImageLoader ]
[ 03-15 23:08:43.806 18124:18124 D/ImageLoader ]
Display image in ImageAware (loaded from DISC_CACHE) [file:///storage/emulated/0/DCIM/OpenCamera/IMG_20190228_122402.jpg_720x1184]

[ 03-15 23:08:43.807 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#IMG_20190228_122402.jpg:setImageViewMatrix setRotationTo 0.0

[ 03-15 23:08:43.807 18124:18124 D/PhotoViewAttacher ]
PhotoViewAttacherEx#IMG_20190228_122402.jpg:setImageViewMatrix setImageDrawable-resetMatrix

[ 03-15 23:08:48.001 18124:18124 E/k3bFoto  ]
LogCat.uncaughtException java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver
android.content.Context.getContentResolver()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()'
on a null object reference
        at de.k3b.android.util.AndroidFileCommands.canProcessFile(AndroidFileCommands.java:526)
        at de.k3b.android.util.AndroidFileCommands.canProcessFile(AndroidFileCommands.java:518)
        at de.k3b.io.FileCommands.moveOrCopyFiles(FileCommands.java:253)
        at de.k3b.android.util.AndroidFileCommands.rename(AndroidFileCommands.java:206)
        at de.k3b.android.androFotoFinder.imagedetail.ImageDetailActivityViewPager.onRenameSubDirAnswer(ImageDetailActivityViewPager.java:1137)
        at de.k3b.android.androFotoFinder.imagedetail.ImageDetailActivityViewPager.access$1300(ImageDetailActivityViewPager.java:94)
        at de.k3b.android.androFotoFinder.imagedetail.ImageDetailActivityViewPager$5.onDialogResult(ImageDetailActivityViewPager.java:1099)
        at de.k3b.android.widget.Dialogs$5.onClick(Dialogs.java:138)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)


```

**Comment by k3b** [comment]
Thanks for the perfect error report. It contains all infos needed to fix the problem.
