### ISSUE TITLE
NullPointerException when starting PhotoAutoprocessingEditActivity without a selected file

### ISSUE THREAD

**Issue by anlalalu** [k3b/APhotoManager#164]
**Describe the bug**

**To Reproduce**
This crash is triggered by an automatic testing tool with this shell instruction:

adb shell am start -n de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.PhotoAutoprocessingEditActivity

**Smartphone (please complete the following information):**
 - Android version [e.g. Android-7.1] : 7.1.0
 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :v0.8.0.191021

**Crash Report**
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: de.k3b.android.androFotoFinder, PID: 1354
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.PhotoAutoprocessingEditActivity}: java.lang.NullPointerException
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.NullPointerException
                                                     at java.io.File.fixSlashes(File.java:185)
                                                     at java.io.File.<init>(File.java:134)
                                                     at de.k3b.android.androFotoFinder.PhotoAutoprocessingEditActivity.getSelectedFiles(PhotoAutoprocessingEditActivity.java:578)
                                                     at de.k3b.android.androFotoFinder.PhotoAutoprocessingEditActivity.onCreate(PhotoAutoprocessingEditActivity.java:139)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)

Since this is triggered by shell instruction rather than user events, do you judge it as a but?

**Comment by k3b** [comment]
Thanks for reporting this problem. 

PhotoAutoprocessingEditActivity is used to edit an Autoprocessing-file ".apm" from a filemanager through action "edit" or "view".

The NullPointerException means that the intent-to start the activity has no mandatory url parameter.
de.k3b.android.androFotoFinder.PhotoAutoprocessingEditActivity.getSelectedFiles(PhotoAutoprocessingEditActivity.java:578)

I do not see this as a real problem and therefore set priority "minor bug"

**Comment by k3b** [comment]
Not a bug
