### ISSUE TITLE
androFotoFinder has NumberFormatException

### ISSUE THREAD

**Issue by ITanCh** [k3b/APhotoManager#73]
### Expected behavior

```
// CRASH: de.k3b.android.androFotoFinder (pid 5018)
// Short Msg: java.lang.NumberFormatException
// Long Msg: java.lang.NumberFormatException: Invalid int: "2512345671234567"
// Build Label: Android/aosp_flo/flo:6.0.1/MOB30P/tianchi10041651:userdebug/test-keys
// Build Changelist: eng.tianchi.20161004.165046
// Build Time: 1475571199000
// java.lang.RuntimeException: Unable to create application de.k3b.android.androFotoFinder.AndroFotoFinderApp: java.lang.NumberFormatException: Invalid int: "2512345671234567"
//  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
//  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
//  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
//  at android.app.ActivityThread.handleBindApplication(<Xposed>)
//  at android.app.ActivityThread.-wrap1(ActivityThread.java)
//  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
//  at android.os.Handler.dispatchMessage(Handler.java:102)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
//  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
// Caused by: java.lang.NumberFormatException: Invalid int: "2512345671234567"
//  at java.lang.Integer.invalidInt(Integer.java:138)
//  at java.lang.Integer.parse(Integer.java:413)
//  at java.lang.Integer.parseInt(Integer.java:367)
//  at java.lang.Integer.parseInt(Integer.java:334)
//  at java.lang.Integer.valueOf(Integer.java:525)
//  at de.k3b.android.androFotoFinder.SettingsActivity.getPref(SettingsActivity.java:280)
//  at de.k3b.android.androFotoFinder.SettingsActivity.prefs2Global(SettingsActivity.java:182)
//  at de.k3b.android.androFotoFinder.AndroFotoFinderApp.onCreate(AndroFotoFinderApp.java:72)
//  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
//  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
//  ... 12 more
//
```
### Actual behavior

...
### Environment
- Android Version (i.e. 5.1):
  - 6.0.1
- [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :
  - 0.5.3.160927
- Affected Module:
  - androFotoFinder

**Comment by k3b** [comment]
This seems to be a settingsvalue that is not compatibel with previous version any more.

As a hotfix you can clear the app data via settings/appInfo/clearData.

I will further analyse what exatly has happend.

**Comment by k3b** [comment]
Fix will be available in next release
