### ISSUE TITLE
APM-0.6.1 Crashes on Android-7.1 - app doesn't open.

### ISSUE THREAD

**Issue by gppixelworks** [k3b/APhotoManager#96]
### Expected behavior

A Photo Manager to start/open

### Actual behavior

Crashes. Does not start. Only a warning dialogue stating the app couldn't start.

### Environment

* Android Version (i.e. 5.1):
  * 7.1.1, non-rooted Moto E4 Plus
* [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :
  * 0.6.1.170803 (Note: Prior version starts OK.)
* Affected Module:
	* [x ] [Gallery-View](https://github.com/k3b/APhotoManager/wiki/Gallery-View)
	* [ ] [Geographic-Map](https://github.com/k3b/APhotoManager/wiki/geographic-map)
	* [x ] [Image-View](https://github.com/k3b/APhotoManager/wiki/Image-View)
	* [x ] [Filtering](https://github.com/k3b/APhotoManager/wiki/Filter-View)
	* [x ] [Folder-Picker](https://github.com/k3b/APhotoManager/wiki/Folder-Picker)
	* [x ] [Settings](https://github.com/k3b/APhotoManager/wiki/settings)
	* [x ] [Intent API](https://github.com/k3b/APhotoManager/wiki/intentapi)

**Comment by k3b** [comment]
thanks for the error report. 

Unfortunately i donot have an android-7.1 device  to reproduce the problem on my own.
 (i only have android-4.2 and android-4.4 devices :-( )

But may be you can help me to find out what happend.
Can you add some latest crash logfiles to this ticket?

When APhotoManager crashes it tries to write a crash log file

* .../copy/log/androFotofinder.logcat-2017....txt

(for the used crash log path on your device see APhotoManager-Settings-Diagnostics- **Error Log Folder** )

**Comment by k3b** [comment]
Can anybody with an android-7.1 device provide me crashlog of this issue? does it happen on any android-7.1 or only incertain configs?

**Comment by bopfr** [comment]
Log from a galaxy S5, with lineageOs (7.1.2 rooted)
I hope this will help

--------- beginning of main
[ 08-13 22:18:16.313 27558:27558 I/k3bFoto  ]
A Photo Manager 0.6.1.170803 created

[ 08-13 22:18:16.575 27558:27611 W/ExifInterface ]
Skip the tag entry since tag number is not defined: 2

[ 08-13 22:18:17.046 27558:27616 W/ExifInterface ]
Skip the tag entry since tag number is not defined: 2

[ 08-13 22:18:17.052 27558:27615 W/ExifInterface ]
Skip the tag entry since tag number is not defined: 2

[ 08-13 22:18:34.536 27558:27664 W/ExifInterface ]
Skip the tag entry since tag number is not defined: 2

[ 08-13 22:18:34.912 27558:27618 W/ExifInterface ]
Skip the tag entry since tag number is not defined: 2

[ 08-13 22:18:38.860 27558:27665 W/ExifInterface ]
Skip the tag entry since tag number is not defined: 2

[ 08-13 22:19:06.563 27558:27558 E/k3bFoto  ]
LogCat.uncaughtException java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4556)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at de.k3b.io.DirectoryFormatter.parseLatLon(DirectoryFormatter.java:134)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.loadSettingsAndInstanceState(FotoGalleryActivity.java:326)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.access$600(FotoGalleryActivity.java:126)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity.onCreate(FotoGalleryActivity.java:453)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 10 more


[ 08-13 22:19:06.564 27558:27558 E/k3bFoto  ]
saving errorlog ('LocCat') to /storage/emulated/0/copy/log/androFotofinder.logcat-20170813-201906.txt

--------- beginning of crash
[ 08-13 22:19:10.886 27819:27819 I/k3bFoto  ]
A Photo Manager 0.6.1.170803 created

[ 08-13 22:19:10.966 27819:27819 E/k3bFoto  ]
LogCat.uncaughtException java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at de.k3b.io.DirectoryFormatter.parseLatLon(DirectoryFormatter.java:134)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.loadSettingsAndInstanceState(FotoGalleryActivity.java:326)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.access$600(FotoGalleryActivity.java:126)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity.onCreate(FotoGalleryActivity.java:453)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more


[ 08-13 22:19:10.966 27819:27819 E/k3bFoto  ]
saving errorlog ('LocCat') to /storage/emulated/0/copy/log/androFotofinder.logcat-20170813-201910.txt

[ 08-13 22:19:20.233 27900:27900 I/k3bFoto  ]
A Photo Manager 0.6.1.170803 created

[ 08-13 22:19:20.315 27900:27900 E/k3bFoto  ]
LogCat.uncaughtException java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at de.k3b.io.DirectoryFormatter.parseLatLon(DirectoryFormatter.java:134)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.loadSettingsAndInstanceState(FotoGalleryActivity.java:326)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.access$600(FotoGalleryActivity.java:126)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity.onCreate(FotoGalleryActivity.java:453)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more


[ 08-13 22:19:20.316 27900:27900 E/k3bFoto  ]
saving errorlog ('LocCat') to /storage/emulated/0/copy/log/androFotofinder.logcat-20170813-201920.txt

[ 08-13 22:19:58.595 28008:28008 I/k3bFoto  ]
A Photo Manager 0.6.1.170803 created

[ 08-13 22:19:58.668 28008:28008 E/k3bFoto  ]
LogCat.uncaughtException java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at de.k3b.io.DirectoryFormatter.parseLatLon(DirectoryFormatter.java:134)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.loadSettingsAndInstanceState(FotoGalleryActivity.java:326)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.access$600(FotoGalleryActivity.java:126)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity.onCreate(FotoGalleryActivity.java:453)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more


[ 08-13 22:19:58.669 28008:28008 E/k3bFoto  ]
saving errorlog ('LocCat') to /storage/emulated/0/copy/log/androFotofinder.logcat-20170813-201958.txt

[ 08-13 22:20:13.890 28056:28056 I/k3bFoto  ]
A Photo Manager 0.6.1.170803 created

[ 08-13 22:20:13.968 28056:28056 E/k3bFoto  ]
LogCat.uncaughtException java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at de.k3b.io.DirectoryFormatter.parseLatLon(DirectoryFormatter.java:134)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.loadSettingsAndInstanceState(FotoGalleryActivity.java:326)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.access$600(FotoGalleryActivity.java:126)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity.onCreate(FotoGalleryActivity.java:453)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more


[ 08-13 22:20:13.969 28056:28056 E/k3bFoto  ]
saving errorlog ('LocCat') to /storage/emulated/0/copy/log/androFotofinder.logcat-20170813-202013.txt

[ 08-13 22:20:20.924 28117:28117 I/k3bFoto  ]
A Photo Manager 0.6.1.170803 created

[ 08-13 22:20:21.004 28117:28117 I/OsmDroid ]
Using tile source: Mapnik

[ 08-13 22:20:21.020 28117:28117 I/OsmDroid ]
sdcard state: mounted

[ 08-13 22:20:21.026 28117:28117 I/OsmDroid ]
sdcard state: mounted

[ 08-13 22:20:21.039 28117:28135 D/OsmDroid ]
Local storage cahce purged 16 expired tiles in 26ms, cache size is 20480bytes

[ 08-13 22:20:21.053 28117:28117 I/OsmDroid ]
sdcard state: mounted

[ 08-13 22:20:21.176 28117:28117 I/OsmDroid ]
rescale tile cache from 0 to 2

[ 08-13 22:20:21.182 28117:28117 I/OsmDroid ]
Finished rescale in 6ms

[ 08-13 22:20:21.275 28117:28117 I/OsmDroid ]
Tile cache increased from 9 to 48

[ 08-13 22:20:21.589 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/3/3

[ 08-13 22:20:21.597 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/3/2

[ 08-13 22:20:21.676 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/0/1

[ 08-13 22:20:21.784 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/1/3

[ 08-13 22:20:21.794 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/3/1

[ 08-13 22:20:21.857 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/1/1

[ 08-13 22:20:21.880 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/2/1

[ 08-13 22:20:21.973 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/2/3

[ 08-13 22:20:21.984 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/1/0

[ 08-13 22:20:22.041 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/0/3

[ 08-13 22:20:22.051 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/1/2

[ 08-13 22:20:22.111 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/3/0

[ 08-13 22:20:22.120 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/0/0

[ 08-13 22:20:22.183 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/2/0

[ 08-13 22:20:22.192 28117:28152 D/OsmDroid ]
tile inserted Mapnik/2/2/2

[ 08-13 22:20:22.241 28117:28151 D/OsmDroid ]
tile inserted Mapnik/2/0/2

[ 08-13 22:50:13.346 28117:28117 E/k3bFoto  ]
LogCat.uncaughtException java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at de.k3b.io.DirectoryFormatter.parseLatLon(DirectoryFormatter.java:134)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.loadSettingsAndInstanceState(FotoGalleryActivity.java:326)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity$GalleryQueryParameter.access$600(FotoGalleryActivity.java:126)
	at de.k3b.android.androFotoFinder.FotoGalleryActivity.onCreate(FotoGalleryActivity.java:453)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more


[ 08-13 22:50:13.347 28117:28117 E/k3bFoto  ]
saving errorlog ('LocCat') to /storage/emulated/0/copy/log/androFotofinder.logcat-20170813-205013.txt

**Comment by k3b** [comment]
great, this helps a lot

**Comment by k3b** [comment]
I just published the bugfix release v0.6.1.170816 (32) . This should be available soon on fdroid and uptodown.com

**Comment by k3b** [comment]
@gppixelworks , @bopfr and other users who had this issue: the bugfix release is now available at fdroid and uptodown. can anybody confirm that the problem is gone?

**Comment by bopfr** [comment]
I just updated on fdroid. It works well for me. Just a question: Is there a way to see files on a usb device (card reader or USB stick ).
Thanks for your work.

**Comment by k3b** [comment]
thanks for the quick feedback.

@bopfr 

>  Is there a way to see files on a usb device (card reader or USB stick ).

In theory yes if you add the media to the media-database.

* ask apm-media scanner to include the media via gallery-menu/more/media-scanner.

**danger:** I donot know what happens if you remove the usb so the media-database contain entries to non exisitent files.

I have all my images on a sd-card that is never removed.

**Comment by bopfr** [comment]
Media scanner does not show anything
(Screenshot)
The mount point is here
(Screenshot)
2E1E-02A6 is my sdcard.
F8F7-24D3 is the otg device (USB stick).
I think apm can not reach this location

Bop

Le 21 août 2017 7:20 PM, "k3b" <notifications@github.com> a écrit :

thanks for the quick feedback.

@bopfr <https://github.com/bopfr>

Is there a way to see files on a usb device (card reader or USB stick ).

In theory yes if you add the media to the media-database.

   - ask apm-media scanner to include the media via
   gallery-menu/more/media-scanner.

*danger:* I donot know what happens if you remove the usb so the
media-database contain entries to non exisitent files.

I have all my images on a sd-card that is never removed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/k3b/APhotoManager/issues/96#issuecomment-323803015>,
or mute
the thread
